### ISSUE TITLE
Bad mount command causing spurious remount failures?

### ISSUE THREAD

**Issue by richfelker** [Stericson/RootTools#73]
See this issue on /system/app mover:

https://github.com/j4velin/SystemAppMover/issues/14

I don't think the description there is quite correct, since both forms of the command work for me, but I am getting spurious "Could not remount /system" errors even when /system is already mounted rw, and it looks plausible that RootTools is the source of the problem.

**Comment by berturion** [comment]
I am on official LineageOS 14.1 (Android 7.1.2) on a Oneplus 3T, Busybox 1.27.2. /system/app mover 1.7.2. I cannot move any app to system because of this error. Even if I manually mount /system in rw before moving an app to system.

I used:

    mount -o rw,remount /system
or

    busybox mount -o rw,remount /system

But the error is still there.

The library for mounting system is RootTools. I think that RootTools is the origin of this error.

**Comment by Stericson** [comment]
I've updated Roottools to include this method of remounting.

This update should resolve the issue.

**Comment by AntumDeluge** [comment]
So, /system/app mover just needs rebuilt with fixed RootTools?
